name: Update data
on:
  schedule:
    - cron: '* 8 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get data
      run: /usr/bin/curl -s "https://www.seek.com.au/api/jobsearch/v5/search?siteKey=AU-Main&where=All+Australia&keywords=crypto" | jq -r '"\(now | strftime("%d/%m/%Y")),\(.totalCount)"' >> data.csv
    - name: Config git
      run: | 
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: commit data updates
      run: |
        git add .
        git commit -am "data update"
    - name: fetch from main
      run: git fetch origin main
    - name: push code to main
      run: git push origin HEAD:main
