name: Update data
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get data
      run: /usr/bin/curl https://jobsearch-api.cloud.seek.co.nz/search?keywords=crypto
    - run: |
        echo "Got data"