name: Update data
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Get data
      #   uses: actions/checkout@v2
      # - run: /usr/bin/curl -s https://jobsearch-api.cloud.seek.co.nz/search?keywords=crypto | jq -r '.totalCount'
      # - run: |
      #     echo "Got data"
      - uses: actions/checkout@v2 # DamianReeves/write-file-action
        with:
          path: ${{ env.home}}/.bashrc
          contents: |
            echo "Hello World!"
          write-mode: append