name: Update data
on:
  schedule:
    - cron: '*/3 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get data
      run: /usr/bin/curl  -s https://www.seek.com.au/api/chalice-search/v4/search?siteKey=AU-Main&sourcesystem=houston&where=All+Australia&page=1&keywords=crypto | jq -r '"\(now | strftime("%d/%m/%Y")),\(.totalCount)"' >> data.csv
    - name: Config git
      run: git config --local user.name "tbenade"
    - name: commit data updates
      run: git commit -am "data update"
    - name: fetch from main
      run: git fetch origin main
    - name: push code to main
      run: git push origin HEAD:main
